// Generated by gencpp from file ur5_kinematics/IkService.msg
// DO NOT EDIT!


#ifndef UR5_KINEMATICS_MESSAGE_IKSERVICE_H
#define UR5_KINEMATICS_MESSAGE_IKSERVICE_H

#include <ros/service_traits.h>


#include <ur5_kinematics/IkServiceRequest.h>
#include <ur5_kinematics/IkServiceResponse.h>


namespace ur5_kinematics
{

struct IkService
{

typedef IkServiceRequest Request;
typedef IkServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct IkService
} // namespace ur5_kinematics


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ur5_kinematics::IkService > {
  static const char* value()
  {
    return "3ec0d754206886798b3d26a7d01862a6";
  }

  static const char* value(const ::ur5_kinematics::IkService&) { return value(); }
};

template<>
struct DataType< ::ur5_kinematics::IkService > {
  static const char* value()
  {
    return "ur5_kinematics/IkService";
  }

  static const char* value(const ::ur5_kinematics::IkService&) { return value(); }
};


// service_traits::MD5Sum< ::ur5_kinematics::IkServiceRequest> should match
// service_traits::MD5Sum< ::ur5_kinematics::IkService >
template<>
struct MD5Sum< ::ur5_kinematics::IkServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ur5_kinematics::IkService >::value();
  }
  static const char* value(const ::ur5_kinematics::IkServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ur5_kinematics::IkServiceRequest> should match
// service_traits::DataType< ::ur5_kinematics::IkService >
template<>
struct DataType< ::ur5_kinematics::IkServiceRequest>
{
  static const char* value()
  {
    return DataType< ::ur5_kinematics::IkService >::value();
  }
  static const char* value(const ::ur5_kinematics::IkServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ur5_kinematics::IkServiceResponse> should match
// service_traits::MD5Sum< ::ur5_kinematics::IkService >
template<>
struct MD5Sum< ::ur5_kinematics::IkServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ur5_kinematics::IkService >::value();
  }
  static const char* value(const ::ur5_kinematics::IkServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ur5_kinematics::IkServiceResponse> should match
// service_traits::DataType< ::ur5_kinematics::IkService >
template<>
struct DataType< ::ur5_kinematics::IkServiceResponse>
{
  static const char* value()
  {
    return DataType< ::ur5_kinematics::IkService >::value();
  }
  static const char* value(const ::ur5_kinematics::IkServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UR5_KINEMATICS_MESSAGE_IKSERVICE_H
