// Generated by gencpp from file ur5_kinematics/IkServiceRequest.msg
// DO NOT EDIT!


#ifndef UR5_KINEMATICS_MESSAGE_IKSERVICEREQUEST_H
#define UR5_KINEMATICS_MESSAGE_IKSERVICEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ur5_kinematics
{
template <class ContainerAllocator>
struct IkServiceRequest_
{
  typedef IkServiceRequest_<ContainerAllocator> Type;

  IkServiceRequest_()
    : target_x(0.0)
    , target_y(0.0)
    , target_z(0.0)
    , roll(0.0)
    , pitch(0.0)
    , yaw(0.0)
    , joint_prev()  {
    }
  IkServiceRequest_(const ContainerAllocator& _alloc)
    : target_x(0.0)
    , target_y(0.0)
    , target_z(0.0)
    , roll(0.0)
    , pitch(0.0)
    , yaw(0.0)
    , joint_prev(_alloc)  {
  (void)_alloc;
    }



   typedef double _target_x_type;
  _target_x_type target_x;

   typedef double _target_y_type;
  _target_y_type target_y;

   typedef double _target_z_type;
  _target_z_type target_z;

   typedef double _roll_type;
  _roll_type roll;

   typedef double _pitch_type;
  _pitch_type pitch;

   typedef double _yaw_type;
  _yaw_type yaw;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _joint_prev_type;
  _joint_prev_type joint_prev;





  typedef boost::shared_ptr< ::ur5_kinematics::IkServiceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ur5_kinematics::IkServiceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct IkServiceRequest_

typedef ::ur5_kinematics::IkServiceRequest_<std::allocator<void> > IkServiceRequest;

typedef boost::shared_ptr< ::ur5_kinematics::IkServiceRequest > IkServiceRequestPtr;
typedef boost::shared_ptr< ::ur5_kinematics::IkServiceRequest const> IkServiceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ur5_kinematics::IkServiceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ur5_kinematics::IkServiceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ur5_kinematics::IkServiceRequest_<ContainerAllocator1> & lhs, const ::ur5_kinematics::IkServiceRequest_<ContainerAllocator2> & rhs)
{
  return lhs.target_x == rhs.target_x &&
    lhs.target_y == rhs.target_y &&
    lhs.target_z == rhs.target_z &&
    lhs.roll == rhs.roll &&
    lhs.pitch == rhs.pitch &&
    lhs.yaw == rhs.yaw &&
    lhs.joint_prev == rhs.joint_prev;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ur5_kinematics::IkServiceRequest_<ContainerAllocator1> & lhs, const ::ur5_kinematics::IkServiceRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ur5_kinematics

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ur5_kinematics::IkServiceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ur5_kinematics::IkServiceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ur5_kinematics::IkServiceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ur5_kinematics::IkServiceRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ur5_kinematics::IkServiceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ur5_kinematics::IkServiceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ur5_kinematics::IkServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0ba25169bdf8186777bc63a2f0222627";
  }

  static const char* value(const ::ur5_kinematics::IkServiceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0ba25169bdf81867ULL;
  static const uint64_t static_value2 = 0x77bc63a2f0222627ULL;
};

template<class ContainerAllocator>
struct DataType< ::ur5_kinematics::IkServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ur5_kinematics/IkServiceRequest";
  }

  static const char* value(const ::ur5_kinematics::IkServiceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ur5_kinematics::IkServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# 请求数据 Request\n"
"float64 target_x\n"
"float64 target_y\n"
"float64 target_z\n"
"float64 roll\n"
"float64 pitch\n"
"float64 yaw\n"
"float64[] joint_prev\n"
"\n"
;
  }

  static const char* value(const ::ur5_kinematics::IkServiceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ur5_kinematics::IkServiceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.target_x);
      stream.next(m.target_y);
      stream.next(m.target_z);
      stream.next(m.roll);
      stream.next(m.pitch);
      stream.next(m.yaw);
      stream.next(m.joint_prev);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct IkServiceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ur5_kinematics::IkServiceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ur5_kinematics::IkServiceRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "target_x: ";
    Printer<double>::stream(s, indent + "  ", v.target_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "target_y: ";
    Printer<double>::stream(s, indent + "  ", v.target_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "target_z: ";
    Printer<double>::stream(s, indent + "  ", v.target_z);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "roll: ";
    Printer<double>::stream(s, indent + "  ", v.roll);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "pitch: ";
    Printer<double>::stream(s, indent + "  ", v.pitch);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "yaw: ";
    Printer<double>::stream(s, indent + "  ", v.yaw);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "joint_prev: ";
    if (v.joint_prev.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.joint_prev.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<double>::stream(s, true ? std::string() : indent + "    ", v.joint_prev[i]);
    }
    if (v.joint_prev.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // UR5_KINEMATICS_MESSAGE_IKSERVICEREQUEST_H
