// Generated by gencpp from file ur5_kinematics/IkServiceResponse.msg
// DO NOT EDIT!


#ifndef UR5_KINEMATICS_MESSAGE_IKSERVICERESPONSE_H
#define UR5_KINEMATICS_MESSAGE_IKSERVICERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ur5_kinematics
{
template <class ContainerAllocator>
struct IkServiceResponse_
{
  typedef IkServiceResponse_<ContainerAllocator> Type;

  IkServiceResponse_()
    : success(false)
    , error_code(0)
    , max_angle_error_deg(0.0)
    , joint_positions()  {
    }
  IkServiceResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , error_code(0)
    , max_angle_error_deg(0.0)
    , joint_positions(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef int32_t _error_code_type;
  _error_code_type error_code;

   typedef double _max_angle_error_deg_type;
  _max_angle_error_deg_type max_angle_error_deg;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _joint_positions_type;
  _joint_positions_type joint_positions;





  typedef boost::shared_ptr< ::ur5_kinematics::IkServiceResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ur5_kinematics::IkServiceResponse_<ContainerAllocator> const> ConstPtr;

}; // struct IkServiceResponse_

typedef ::ur5_kinematics::IkServiceResponse_<std::allocator<void> > IkServiceResponse;

typedef boost::shared_ptr< ::ur5_kinematics::IkServiceResponse > IkServiceResponsePtr;
typedef boost::shared_ptr< ::ur5_kinematics::IkServiceResponse const> IkServiceResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ur5_kinematics::IkServiceResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ur5_kinematics::IkServiceResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ur5_kinematics::IkServiceResponse_<ContainerAllocator1> & lhs, const ::ur5_kinematics::IkServiceResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.error_code == rhs.error_code &&
    lhs.max_angle_error_deg == rhs.max_angle_error_deg &&
    lhs.joint_positions == rhs.joint_positions;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ur5_kinematics::IkServiceResponse_<ContainerAllocator1> & lhs, const ::ur5_kinematics::IkServiceResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ur5_kinematics

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ur5_kinematics::IkServiceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ur5_kinematics::IkServiceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ur5_kinematics::IkServiceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ur5_kinematics::IkServiceResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ur5_kinematics::IkServiceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ur5_kinematics::IkServiceResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ur5_kinematics::IkServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a095a0545828f197893a43625f09b4c7";
  }

  static const char* value(const ::ur5_kinematics::IkServiceResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa095a0545828f197ULL;
  static const uint64_t static_value2 = 0x893a43625f09b4c7ULL;
};

template<class ContainerAllocator>
struct DataType< ::ur5_kinematics::IkServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ur5_kinematics/IkServiceResponse";
  }

  static const char* value(const ::ur5_kinematics::IkServiceResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ur5_kinematics::IkServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# 响应数据 Response（必须加 --- 分隔！）\n"
"bool success\n"
"int32 error_code\n"
"float64 max_angle_error_deg\n"
"float64[] joint_positions\n"
;
  }

  static const char* value(const ::ur5_kinematics::IkServiceResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ur5_kinematics::IkServiceResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.error_code);
      stream.next(m.max_angle_error_deg);
      stream.next(m.joint_positions);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct IkServiceResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ur5_kinematics::IkServiceResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ur5_kinematics::IkServiceResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "error_code: ";
    Printer<int32_t>::stream(s, indent + "  ", v.error_code);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "max_angle_error_deg: ";
    Printer<double>::stream(s, indent + "  ", v.max_angle_error_deg);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "joint_positions: ";
    if (v.joint_positions.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.joint_positions.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<double>::stream(s, true ? std::string() : indent + "    ", v.joint_positions[i]);
    }
    if (v.joint_positions.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // UR5_KINEMATICS_MESSAGE_IKSERVICERESPONSE_H
